#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config \
  active_window_border_color 0xff775759 \
  active_window_opacity 1.0 \
  auto_balance off \
  bottom_padding 6 \
  focus_follows_mouse off \
  insert_feedback_color 0xffd75f5f \
  layout bsp \
  left_padding 6 \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  mouse_follows_focus off \
  mouse_modifier fn \
  normal_window_border_color 0xff555555 \
  normal_window_opacity 0.50 \
  right_padding 6 \
  split_ratio 0.50 \
  split_type auto \
  top_padding 6 \
  window_animation_duration 0.00 \
  window_animation_frame_rate 120 \
  window_border off \
  window_border_blur on \
  window_border_hidpi on \
  window_border_radius 12 \
  window_border_width 2 \
  window_gap 6 \
  window_opacity on \
  window_opacity_duration 0.50 \
  window_origin_display default \
  window_placement second_child \
  window_shadow off \
  window_topmost off \
  window_zoom_persist on

echo "yabai configuration loaded.."
