#! /usr/bin/env zsh

alias vim=lvim
alias vi=lvim

alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias ga='git add .'
alias gaa='git add -A :/'
alias gc='git commit -m '
alias gca='git commit -a -m '
alias gco='git checkout'
alias gcb='git checkout -b'
alias gpd='git pull'
alias gpu='git push -u origin HEAD'
alias gpp='git pull && git push'

# Aliases
alias l=ll
alias la="ll -a"

alias ec='chezmoi edit --apply'

alias cdp='cd $(npm prefix)'
alias cdg='cd $(git rev-parse --show-toplevel)'

