#! /usr/bin/env zsh

alias vim=nvim
alias vi=nvim

alias ga='git add .'
alias gaa='git add -A :/'
alias gc='git commit -m '
alias gca='git commit -a -m '
alias gbc='git checkout -b'
alias gbl='better_branch'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gpd='git pull'
alias gpp='git pull && git push'
alias gpu='git push -u origin HEAD'
alias gs='git status'
alias gsa='git stash --all'
alias gsl='git stash list'

# Aliases
alias l="ll"
alias la="ll -a"

alias ec='chezmoi edit --apply'

alias cdp='cd $(npm prefix)'
alias cdg='cd $(git rev-parse --show-toplevel)'
